const FA_TEXT = {
    ROUTES_NAME: {
        LOGIN: "ورود به حساب",
        ORDERS: "سفارشات",
        CREATE_ORDER: "ایجاد سفارش",
        DASHBOARD: "داشبورد",
        ORDERS_DETAILS: "جزییات سفارش",
        ORDERS_AGGREGATE: "سفارشات تجمیعی",
        ORDERS_AGGREGATE_ACCEPT: "تایید سفارشات تجمیعی",
        ORDER_AGGREGATE_DETAILS: "جزییات سفارشات تجمیعی",
        SHOPS: "فروشگاه ها",
        SHIPMENTS: "محموله ها",
        SHIPMENT_DETAILS: "جزییات محموله",
        PARCELS: "مرسولات",
        PARCEL_DETAILS: "جزئیات مرسوله",
    },
    ORDERS_TABLE: {
        ID: "شناسه",
        BARCODE: "بارکد",
        STATUS: "وضعیت",
        UPDATED_AT: "تاریخ بروزرسانی",
        CREATED_AT: "تاریخ و ساعت ایجاد",
        SENDER: "فرستنده",
        RECEIVER: "گیرنده",
        DG_ID: "شناسه دیجی‌کالا",
        TRACKING_CODE: "کد رهگیری",
    },
    ORDERS_AGGREGATE_TABLE: {
        ID: "شناسه",
        TITLE: "عنوان",
        STATUS: "وضعیت",
        PROBLEMS: "مسله دار ها",
        TOTAL: "مجموع",
        CREATED_AT: "تاریخ ایجاد",
        ACTIONS: "عملیات",
    },
    ORDER: {
        ID: "شناسه",
        BARCODE: "بارکد",
        STATUS: "وضعیت",
        UPDATED_AT: "تاریخ بروزرسانی",
        ACTIONS: "عملیات",
    },
    SHIPMENT_PARCELS: {
        BARCODE: "بارکد",
        ORDER_ID: "شناسه سفارش",
        RECEIVER_NAME: "نام گیرنده",
        DESTINATION_CITY: "شهر مقصد",
        WEIGHT: "وزن (گرم)",
        VALUE: "ارزش (تومان)",
        STATUS: "وضعیت",
        CREATED_AT: "تاریخ ثبت",
    },
    PARCELS_TABLE: {
        ID: "شناسه",
        BARCODE: "بارکد",
        SHIPMENT_ID: "شناسه محموله",
        SHIPMENT_NAME: "نام محموله",
        ORDER_ID: "شناسه سفارش",
        RECEIVER_NAME: "نام گیرنده",
        DESTINATION_CITY: "شهر مقصد",
        WEIGHT: "وزن (گرم)",
        VALUE: "ارزش (تومان)",
        STATUS: "وضعیت",
        CREATED_AT: "تاریخ ثبت",
    },
    ORDER_TRACKING: {
        ID: "شناسه",
        DATE: "تاریخ",
        ADDRESS: "آدرس",
        STATUS: "وضعیت",
    },
    ORDER_SPEC: {
        WEIGHT: "وزن",
        DIMENSIONS: "ابعاد",
        FRAGILE: "شکستنی",
        LIQUID: "مایعات",
        COST: "هزینه",
        ORDER_VALUE: "ارزش کالا",
    },
    SHOPS_TABLE: {
        ID: "شناسه فروشگاه",
        CAN_OPERATE: "قابل عملیات",
        NAME: "نام",
        POSTAL_CODE: "کدپستی",
        ADDRESS: "آدرس",
        PROVINCE: "استان",
        CITY: "شهر",
        APPROVED: "تایید شده",
    },
    SHOP_FORM: {
        GENERAL_INFO: "اطلاعات عمومی",
        NAME: {
            LABEL: "نام فروشگاه",
            PLACEHOLDER: "نام فروشگاه را وارد کنید (حروف فارسی بین ۲ تا ۵۰ حرف)",
        },
        ENABLED: {
            LABEL: "وضعیت فعال بودن",
        },
        ADDRESS_INFO: "اطلاعات آدرس",
        ADDRESS: {
            POSTAL_CODE: {
                LABEL: "کد پستی",
                PLACEHOLDER: "کد پستی را وارد کنید (۸ عدد)",
            },
            POST_UNIT_ID: {
                LABEL: "شناسه واحد پست",
                PLACEHOLDER: "شناسه واحد پست را وارد کنید",
            },
            CITY_ID: {
                LABEL: "شناسه شهر",
                PLACEHOLDER: "شناسه شهر را وارد کنید",
            },
            POSTNODE_ID: {
                LABEL: "شناسه پست نود",
                PLACEHOLDER: "شناسه پست نود را وارد کنید",
            },
            PROVINCE_ID: {
                LABEL: "شناسه استان",
                PLACEHOLDER: "شناسه استان را وارد کنید",
            },
        },
        CONTACT_INFO: "اطلاعات تماس",
        CONTACT: {
            PHONE: {
                LABEL: "تلفن",
                PLACEHOLDER: "تلفن را وارد کنید (87348734-021)",
            },
            MOBILE: {
                LABEL: "موبایل",
                PLACEHOLDER: "موبایل را وارد کنید (09123456789)",
            },
            EMAIL: {
                LABEL: "ایمیل",
                PLACEHOLDER: "ایمیل را وارد کنید (example@domain.com)",
            },
            WEBSITE_URL: {
                LABEL: "آدرس وبسایت",
                PLACEHOLDER: "آدرس وبسایت را وارد کنید (https://example.com)",
            },
        },
        BANK_ACCOUNT_INFO: "اطلاعات حساب بانکی",
        BANK_ACCOUNT: {
            ACCOUNT_BANK: {
                LABEL: "بانک",
                PLACEHOLDER: "بانک را وارد کنید",
            },
            ACCOUNT_BRANCH_NAME: {
                LABEL: "نام شعبه حساب",
                PLACEHOLDER: "نام شعبه حساب را وارد کنید",
            },
            ACCOUNT_NUMBER: {
                LABEL: "شماره حساب",
                PLACEHOLDER: "شماره حساب را وارد کنید (۱۶ عدد)",
            },
            ACCOUNT_IBAN: {
                LABEL: "شماره شبا",
                PLACEHOLDER: "شماره شبا را وارد کنید (۲۴ عدد)",
            },
            ACCOUNT_OWNER: {
                LABEL: "صاحب حساب",
                PLACEHOLDER: "صاحب حساب را وارد کنید",
            },
        },
        MANAGER_IDENTITY: "هویت مدیر",
        MANAGER: {
            NATIONAL_ID: {
                LABEL: "کد ملی مدیر",
                PLACEHOLDER: "کد ملی مدیر را وارد کنید (۱۰ عدد)",
            },
            NATIONAL_ID_SERIAL: {
                LABEL: "سریال کد ملی مدیر",
                PLACEHOLDER: "سریال کد ملی مدیر را وارد کنید",
            },
            BIRTH_DATE: {
                LABEL: "تاریخ تولد مدیر",
                PLACEHOLDER: "تاریخ تولد مدیر را انتخاب کنید",
            },
            FIRST_NAME: {
                LABEL: "نام",
                PLACEHOLDER: "نام را وارد کنید",
            },
            LAST_NAME: {
                LABEL: "نام خانوادگی",
                PLACEHOLDER: "نام خانوادگی را وارد کنید",
            },
            FATHER_NAME: {
                LABEL: "نام پدر",
                PLACEHOLDER: "نام پدر را وارد کنید",
            },
            CERT_NUMBER: {
                LABEL: "شماره شناسنامه",
                PLACEHOLDER: "شماره شناسنامه را وارد کنید",
            },
            CERT_SERIES: {
                LABEL: "سری شناسنامه",
                PLACEHOLDER: "سری شناسنامه را وارد کنید",
            },
            CERT_SERIAL: {
                LABEL: "سریال شناسنامه",
                PLACEHOLDER: "سریال شناسنامه را وارد کنید",
            },
        },
        COLLECTION_SETTINGS: "تنظیمات جمع آوری",
        SAVE: "ذخیره",
        CANCEL: "انصراف",
    },
    SHIPMENTS_TABLE: {
        SHIPMENT_ID: "کد محموله",
        CREATED_AT: "تاریخ ایجاد",
        TOTAL_PARCELS: "تعداد کل",
        FAILED_PARCELS: "ناموفق ها",
        TITLE: "نام محموله",
        STATUS: "وضعیت",
        DOWNLOAD_INVOICE: "دانلود فاکتور",
    },
    SHIPMENT_STATUSES: {
        PENDING: "در انتظار ارسال",
        PROCESSING: "در حال ارسال",
        DELIVERED: "تکمیل شده",
        CANCELED: "لغو شده",
    },
    PARCEL_STATUSES: {
        PENDING: "در انتظار ارسال",
        PROCESSING: "در حال ارسال",
        DELIVERED: "تکمیل شده",
        CANCELED: "لغو شده",
    },
    UPLOAD_EXCEL_FILE: "بارگذاری فایل اکسل",
    UPLOAD: {
        DRAG_OR_CLICK: "فایل را اینجا بکشید یا کلیک کنید",
        UPLOADING: "در حال آپلود...",
        HINT: "حداکثر حجم فایل: ",
        INVALID_TYPE_ERR: "نوع فایل نامعتبر است\n فرمت های معتبر: ",
        INVALID_FILE_VOLUME: "حجم فایل بیش از حد مجاز است\n حداکثر حجم فایل: ",
    },
    DOWNLOAD_BARCODE: "دانلود بارکد",
    DOWNLOAD_EXCEL: "دانلود اکسل",
    SEARCH_BARCODE: "جستجوی بارکد",
    SEARCH: "جستجوی",
    PRINT_BARCODE: "چاپ بارکد",
    PRINT: "چاپ",
    DOWNLOAD_INVOICE_ALL: "دانلود فاکتور همه",
    DOWNLOAD_INVOICE_SELECTED: "دانلود فاکتور {count} مورد",
    GENERATING_INVOICE: "در حال تولید فاکتور...",
    INVOICE_GENERATION_ERROR: "خطا در تولید فاکتور",
    INVOICE_TEMPLATE: {
        SENDER: "فرستنده:",
        RECEIVER: "گیرنده:",
        WEIGHT: "وزن:",
        VALUE: "ارزش:",
        SIZE: "سایز:",
        REGISTRATION_DATE: "تاریخ ثبت:",
        ORDER_ID: "شناسه سفارش:",
        POSTAL_CODE: "کد پستی:",
        GRAMS: "گرم",
        TOMANS: "تومان",
        WARNING: "در صورت مغایرت اطلاعات، از تحویل خودداری نمایید.",
        TRACKING: "رهگیری:",
        TRACKING_URL: "https://tracking.post.ir/?id=",
        NO_PARCELS_SELECTED: "هیچ مرسوله‌ای انتخاب نشده است",
        INVOICE_GENERATED_SUCCESS: "فاکتور با موفقیت تولید شد:",
    },
    INVOICE: "فاکتور",
    ACCEPT: "تایید",
    TRACKING_POST: "رهگیری پست",
    TRACKING_FROM_POST: "رهگیری از سایت پست",
    Filter: "فیلتر",
    DONE: "اعمال",
    CLEAR_FILTER: "حذف فیلترها",
    ERROR: "خطا",
    BARCODE_SEARCH: "جستجوی بارکد",
    TODAY: "امروز",
    THIS_MONTH: "این ماه",
    TOTAL: "کل",
    TOTAL_COUNT: "تعداد کل",
    CHOOSE: "انتخاب",
    CREATE_NEW_SHOP: "ساخت فروشگاه جدید",
    UPDATE_SHOP: "آپدیت فروشگاه",
    IS_REQUIRED: "الزامی است",
    THIS_FIELD: "این فیلد",
    INVALID_FORMAT: "فرمت نامعتبر دارد",
    YES: "بله",
    NO: "خیر",
    BARCODE_SEARCH_FAILED: "مرسوله ای با این کد رهگیری وجود ندارد.",
    ENABLE: "فعال",
    DISABLE: "غیر فعال",
    CREATE_ORDER_PAGE: {
        TITLE: "ایجاد سفارش",
        DESC: "فايل اكسل يا CSV حاوى سفارشات خود را باركذارى كنيد تا فرآيند ثبت و ارسال آغاز شود",
        DOWNLOAD_SAMPLE: "دانلود فایل نمونه",
        VALIDATION_RESULT: {
            TITLE: "نتیجه اعتبارسنجی فایل",
            TOTAL_ORDERS: "کل سفارشات",
            VALID_ORDERS: "سفارشات معتبر",
            INVALID_ORDERS: "سفارشات نامعتبر",
            ERROR_LIST: "لیست خطاها:",
            RE_UPLOAD: "بارگذاری مجدد",
        },
    },
    failures: "ناموفق ها",
    PARCEL_DETAILS_PAGE: {
        RECIPIENT_INFO: "اطلاعات گیرنده",
        NAME: "نام",
        PHONE: "شماره تماس",
        ADDRESS: "آدرس",
        STATUS: "وضعیت",
        WEIGHT: "وزن کل",
        ORDER_DATE: "تاریخ سفارش",
        SHIPPING_SERVICE: "سرویس ارسال",
        TRACKING_CODE: "کد رهگیری",
        PARCEL_INFO: "اطلاعات مرسوله"
    },
    DOWNLOAD_INVOICE: "دانلود فاکتور",
    GRAM: "گرم",
    LOGOUT: {
        TEXT: "آیا از خروج از حساب خود اطمینان دارید؟",
        TITLE: "خروج از حساب"
    },
    ERROR_PAGE: {
        TEXT: "مشگلی پیش آمده. لطفا صفحه را رفرش کنید."
    },
    LOGIN_PAGE: {
        LOGIN_SUCCESS: "ورود با موفقیت انجام شد"
    }
}

export default FA_TEXT