export enum PaymentDiscountType {
  Percentage = 0,
  FixedAmount = 1,
}

export enum PaymentDiscountValueIdType {
  Course = 1,
  Category = 2,
}

export enum PaymentDiscountCodeCreationRqType {
  AutoGenerated = 1,
  ClientProvided = 2,
}

export const getDiscountTypeName = (type: PaymentDiscountType): string => {
  switch (type) {
    case PaymentDiscountType.Percentage:
      return 'درصدی';
    case PaymentDiscountType.FixedAmount:
      return 'مبلغ ثابت';
    default:
      return 'نامشخص';
  }
};

export const getDiscountTypeColor = (type: PaymentDiscountType): string => {
  switch (type) {
    case PaymentDiscountType.Percentage:
      return 'blue';
    case PaymentDiscountType.FixedAmount:
      return 'green';
    default:
      return 'default';
  }
};

export const getValueIdTypeName = (type: PaymentDiscountValueIdType): string => {
  switch (type) {
    case PaymentDiscountValueIdType.Course:
      return 'دوره';
    case PaymentDiscountValueIdType.Category:
      return 'دسته‌بندی';
    default:
      return 'نامشخص';
  }
};

export interface DiscountValueSummary {
  id: string;
  name: string | null;
}

export interface DiscountCode {
  id: string;
  code: string;
  type: PaymentDiscountType;
  value: number;
  maxUsageCount: number;
  usageCount: number;
  isActive: boolean;
  validStartTime: string | null;
  validEndTime: string | null;
  valueIdType: PaymentDiscountValueIdType;
  values: DiscountValueSummary[];
  createdTime: string | null;
  updatedTime: string | null;
}

export interface GetAllDiscountCodesParams {
  PageIndex: number;
  PageSize: number;
  Code?: string;
  IsActive?: boolean;
}

export interface AllDiscountCodesResponse {
  items: DiscountCode[];
  totalCount: number;
}

export interface CreateDiscountCodePayload {
  creationRqType: PaymentDiscountCodeCreationRqType;
  code?: string;
  type: PaymentDiscountType;
  value: number;
  maxUsageCount: number;
  isActive: boolean;
  validStartTime?: string;
  validEndTime?: string;
  valueIdType: PaymentDiscountValueIdType;
  valueIds?: string[];
}

export interface UpdateDiscountCodePayload {
  id: string;
  type: PaymentDiscountType;
  value: number;
  maxUsageCount: number;
  isActive: boolean;
  validStartTime?: string;
  validEndTime?: string;
  valueIdType: PaymentDiscountValueIdType;
  valueIds?: string[];
}
