import React, { useEffect } from 'react';
import {
  Modal,
  Form,
  Input,
  InputNumber,
  Switch,
  Select,
  Radio,
  Divider,
  Row,
  Col,
  Alert,
} from 'antd';
import { Tag as TagIcon } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import moment from 'moment-jalaali';
import DatePicker from '@/components/datePicker/DatePicker';
import { courseService } from '@/services';
import { categoryService } from '@/services';
import {
  DiscountCode,
  PaymentDiscountType,
  PaymentDiscountValueIdType,
  PaymentDiscountCodeCreationRqType,
  CreateDiscountCodePayload,
  UpdateDiscountCodePayload,
} from '@/types/discountCode.types';

interface DiscountCodeModalProps {
  open: boolean;
  discountCode: DiscountCode | null;
  onClose: () => void;
  onCreate: (payload: CreateDiscountCodePayload) => Promise<void>;
  onUpdate: (payload: UpdateDiscountCodePayload) => Promise<void>;
  loading: boolean;
}

const DISCOUNT_TYPE_OPTIONS = [
  { value: PaymentDiscountType.Percentage, label: 'درصدی (%)' },
  { value: PaymentDiscountType.FixedAmount, label: 'مبلغ ثابت (تومان)' },
];

const VALUE_ID_TYPE_OPTIONS = [
  { value: PaymentDiscountValueIdType.Course, label: 'دوره' },
  { value: PaymentDiscountValueIdType.Category, label: 'دسته‌بندی' },
];

export const DiscountCodeModal: React.FC<DiscountCodeModalProps> = ({
  open,
  discountCode,
  onClose,
  onCreate,
  onUpdate,
  loading,
}) => {
  const [form] = Form.useForm();
  const isEditMode = !!discountCode;

  const creationRqType: PaymentDiscountCodeCreationRqType = Form.useWatch('creationRqType', form);
  const discountType: PaymentDiscountType = Form.useWatch('type', form);
  const valueIdType: PaymentDiscountValueIdType = Form.useWatch('valueIdType', form);

  // Fetch courses for multi-select
  const { data: coursesData } = useQuery({
    queryKey: ['courses-for-discount-select'],
    queryFn: () => courseService.getAll({ PageIndex: 1, PageSize: 500 }),
    enabled: open && valueIdType === PaymentDiscountValueIdType.Course,
    select: (data) => data.items,
  });

  // Fetch categories for multi-select
  const { data: categoriesData } = useQuery({
    queryKey: ['categories-for-discount-select'],
    queryFn: () => categoryService.getAll(),
    enabled: open && valueIdType === PaymentDiscountValueIdType.Category,
  });

  useEffect(() => {
    if (open && discountCode) {
      form.setFieldsValue({
        type: discountCode.type,
        value: discountCode.value,
        maxUsageCount: discountCode.maxUsageCount,
        isActive: discountCode.isActive,
        valueIdType: discountCode.valueIdType,
        valueIds: discountCode.values.map((v) => v.id),
        validStartTime: discountCode.validStartTime
          ? moment(discountCode.validStartTime).format('YYYY/MM/DD')
          : null,
        validEndTime: discountCode.validEndTime
          ? moment(discountCode.validEndTime).format('YYYY/MM/DD')
          : null,
      });
    } else if (open) {
      form.resetFields();
      form.setFieldsValue({
        creationRqType: PaymentDiscountCodeCreationRqType.AutoGenerated,
        type: PaymentDiscountType.Percentage,
        isActive: true,
        valueIdType: PaymentDiscountValueIdType.Course,
        maxUsageCount: 1,
      });
    }
  }, [open, discountCode, form]);

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();

      const validStartTime = values.validStartTime
        ? moment(values.validStartTime, ['YYYY/MM/DD', 'YYYY-MM-DD']).toISOString()
        : undefined;
      const validEndTime = values.validEndTime
        ? moment(values.validEndTime, ['YYYY/MM/DD', 'YYYY-MM-DD']).toISOString()
        : undefined;

      if (isEditMode && discountCode) {
        await onUpdate({
          id: discountCode.id,
          type: values.type,
          value: values.value,
          maxUsageCount: values.maxUsageCount,
          isActive: values.isActive,
          validStartTime,
          validEndTime,
          valueIdType: values.valueIdType,
          valueIds: values.valueIds?.length ? values.valueIds : undefined,
        });
      } else {
        await onCreate({
          creationRqType: values.creationRqType,
          code:
            values.creationRqType === PaymentDiscountCodeCreationRqType.ClientProvided
              ? values.code
              : undefined,
          type: values.type,
          value: values.value,
          maxUsageCount: values.maxUsageCount,
          isActive: values.isActive,
          validStartTime,
          validEndTime,
          valueIdType: values.valueIdType,
          valueIds: values.valueIds?.length ? values.valueIds : undefined,
        });
      }

      onClose();
    } catch {
      // validation error
    }
  };

  const valueOptions =
    valueIdType === PaymentDiscountValueIdType.Course
      ? (coursesData ?? []).map((c) => ({ value: c.id, label: c.name }))
      : (categoriesData ?? []).map((c) => ({ value: c.id, label: c.name }));

  return (
    <Modal
      title={
        <div className="flex items-center gap-2">
          <TagIcon size={20} style={{ color: '#4B26AD' }} />
          <span>{isEditMode ? 'ویرایش کد تخفیف' : 'ایجاد کد تخفیف جدید'}</span>
        </div>
      }
      open={open}
      onCancel={onClose}
      onOk={handleSubmit}
      okText={isEditMode ? 'ذخیره تغییرات' : 'ایجاد'}
      cancelText="انصراف"
      confirmLoading={loading}
      width={640}
      centered
      destroyOnClose
    >
      <Form form={form} layout="vertical" size="large" className="pt-3">
        {/* Creation type — create only */}
        {!isEditMode && (
          <>
            <Form.Item
              name="creationRqType"
              label="نوع تولید کد"
              rules={[{ required: true }]}
            >
              <Radio.Group>
                <Radio value={PaymentDiscountCodeCreationRqType.AutoGenerated}>
                  خودکار
                </Radio>
                <Radio value={PaymentDiscountCodeCreationRqType.ClientProvided}>
                  دستی (تعیین کد)
                </Radio>
              </Radio.Group>
            </Form.Item>

            {creationRqType === PaymentDiscountCodeCreationRqType.ClientProvided && (
              <Form.Item
                name="code"
                label="کد تخفیف"
                rules={[{ required: true, message: 'کد تخفیف را وارد کنید' }]}
              >
                <Input
                  placeholder="مثال: SUMMER20"
                  style={{ direction: 'ltr', fontFamily: 'monospace' }}
                  maxLength={50}
                />
              </Form.Item>
            )}

            <Divider style={{ marginTop: 4, marginBottom: 16 }} />
          </>
        )}

        {/* Discount type + value */}
        <Row gutter={12}>
          <Col span={12}>
            <Form.Item
              name="type"
              label="نوع تخفیف"
              rules={[{ required: true, message: 'نوع تخفیف را انتخاب کنید' }]}
            >
              <Select options={DISCOUNT_TYPE_OPTIONS} />
            </Form.Item>
          </Col>
          <Col span={12}>
            <Form.Item
              name="value"
              label={
                discountType === PaymentDiscountType.Percentage
                  ? 'مقدار تخفیف (%)'
                  : 'مقدار تخفیف (تومان)'
              }
              rules={[
                { required: true, message: 'مقدار تخفیف را وارد کنید' },
                { type: 'number', min: 0, message: 'مقدار باید بزرگتر از صفر باشد' },
                ...(discountType === PaymentDiscountType.Percentage
                  ? [{ type: 'number' as const, max: 100, message: 'درصد نمی‌تواند بیشتر از ۱۰۰ باشد' }]
                  : []),
              ]}
            >
              <InputNumber
                className="w-full"
                min={0}
                max={discountType === PaymentDiscountType.Percentage ? 100 : undefined}
                step={discountType === PaymentDiscountType.Percentage ? 1 : 1000}
                addonAfter={
                  discountType === PaymentDiscountType.Percentage ? '٪' : 'تومان'
                }
              />
            </Form.Item>
          </Col>
        </Row>

        {/* Max usage + active */}
        <Row gutter={12}>
          <Col span={12}>
            <Form.Item
              name="maxUsageCount"
              label="حداکثر تعداد استفاده"
              rules={[
                { required: true, message: 'تعداد را وارد کنید' },
                { type: 'number', min: 1, message: 'حداقل ۱ باشد' },
              ]}
            >
              <InputNumber className="w-full" min={1} />
            </Form.Item>
          </Col>
          <Col span={12}>
            <Form.Item name="isActive" label="وضعیت" valuePropName="checked">
              <Switch checkedChildren="فعال" unCheckedChildren="غیرفعال" />
            </Form.Item>
          </Col>
        </Row>

        {/* Validity dates */}
        <Divider orientation="right" plain style={{ marginTop: 0 }}>
          بازه اعتبار (اختیاری)
        </Divider>
        <Row gutter={12}>
          <Col span={12}>
            <DatePicker
              isFormItem
              name="validStartTime"
              label="از تاریخ"
              placeholder="انتخاب تاریخ شروع"
              allowClear
              disabled={false}
              showTime={false}
            />
          </Col>
          <Col span={12}>
            <DatePicker
              isFormItem
              name="validEndTime"
              label="تا تاریخ"
              placeholder="انتخاب تاریخ پایان"
              allowClear
              disabled={false}
              showTime={false}
            />
          </Col>
        </Row>

        {/* Scope restriction */}
        <Divider orientation="right" plain style={{ marginTop: 0 }}>
          محدوده اعمال (اختیاری)
        </Divider>
        <Form.Item
          name="valueIdType"
          label="نوع محدوده"
          rules={[{ required: true }]}
        >
          <Select options={VALUE_ID_TYPE_OPTIONS} />
        </Form.Item>

        <Form.Item name="valueIds" label="محدود به (خالی = همه)">
          <Select
            mode="multiple"
            allowClear
            placeholder={
              valueIdType === PaymentDiscountValueIdType.Course
                ? 'انتخاب دوره‌ها...'
                : 'انتخاب دسته‌بندی‌ها...'
            }
            options={valueOptions}
            filterOption={(input, option) =>
              String(option?.label ?? '')
                .toLowerCase()
                .includes(input.toLowerCase())
            }
            showSearch
            maxTagCount="responsive"
          />
        </Form.Item>

        {isEditMode && (
          <Alert
            type="info"
            showIcon
            message={`کد: ${discountCode?.code}`}
            className="mt-2"
            style={{ direction: 'ltr', fontFamily: 'monospace', textAlign: 'left' }}
          />
        )}
      </Form>
    </Modal>
  );
};
